- length: 2
  name: Sex # Пол
  values:
    - Мужской
    - Женский

- length: 4
  name: Age # Возраст
  values:
    - Ребенок
    - Молодой
    - Взрослый
    - Пожилой

- length: 3
  name: Skin_Color # Цвет кожи
  values:
    - Белый
    - Черный
    - Невозможно определить

- length: 2
  name: Headwear # Головной убор
  values:
    - Есть
    - Нет

- length: 5
  name: Hair_color # Цвет волос
  values:
    - Лысый
    - Белые
    - Темные
    - Цветные
    - Не видно

- length: 3
  name: Glasses # Очки
  values:
    - Есть
    - Нет
    - Не видно

- length: 2
  name: Scarf # Платок
  values:
    - Есть
    - Нет

- length: 2
  name: Backpack # Рюкзак
  values:
    - Есть
    - Нет

- length: 8
  name: Main_Color # Цвет одежды
  values:
    - Белый
    - Красный
    - Желтый
    - Зеленый
    - Синий
    - Серый
    - Коричневый
    - Черный

- length: 6
  name: UpperBodyWearType # Тип одежды
  values:
    - Футболка
    - Пиджак или Жакет
    - Куртка
    - Кофта или толстовка
    - Жилет
    - Рубашка