all_attributes:
  [ 'Filepath',
    'Sex',
    'Age',
    'Skin_Color',
    'Facial_Hair',
    'Headwear',
    'Headwear_Color',
    'Hood',
    'Headphones',
    'Hair_Length',
    'Hair_color',
    'Glasses',
    'Mask',
    'Scarf',
    'Backpack',
    'Shoulder_Straps',
    'Main_Color',
    'Addition_Color',
    'UpperBodyWearType',
    'Carring']