defaults:
  - _self_
  - version: example_fullbody.yaml
  - override /hydra/job_logging: none
  - override /hydra/hydra_logging: none

hydra:
  run:
    dir: outputs/${version.Name}
  sweep:
    dir: outputs/${version.Name}
    subdir: ${hydra.job.override_dirname}
  job:
    chdir: True

Data:
  data directory: /workspace/data

  train dataset: fullbody_train
  val dataset: fullbody_val
  test datasets:
    - name: fullbody_test

Wandb:
  enabled: false
  account_key: '3bff8c661180b6af3727e36c470dd033e785414c'
  run_offline: False
  run:
    name: ${version.Name}
    project: 'attributes'
    tags: ['Experiment stages']
    group: None
