defaults:
  - _self_
  - version: baseline
  - override /hydra/job_logging: none
  - override /hydra/hydra_logging: none

hydra:
  run:
    dir: outputs/mining
  sweep:
    dir: outputs/mixups
    subdir: ${hydra.job.override_dirname}
  job:
    chdir: True

Run:
  mode: models
  models:
    - 'outputs/stochastic_depth/version.Model.architecture.stochastic_depth_p=0.0,version=stochastic_depth_comparation'
    - 'outputs/stochastic_depth/version.Model.architecture.stochastic_depth_p=0.1,version=stochastic_depth_comparation'
    - 'outputs/stochastic_depth/version.Model.architecture.stochastic_depth_p=0.5,version=stochastic_depth_comparation'
    - 'outputs/moco/version=moco_lup_cropped'
Data:
  data directory: /workspace/data

  test datasets:
    - name: mining_sorce
