- image dir: Bags/BagsStage2/train
  markup: train.json
- image dir: Bags/BagsStage2/test
  markup: test.json
- image dir: Bags/BagsStage2/val
  markup: val.json
- image dir: Bags/BagsStage3/images
  markup: markup.json
- image dir: Bags/BagsStage4/images
  markup: markup.json
- image dir: Bags/BagsStage5/images
  markup: markup.json
- image dir: Bags/BagsStage7/images
  markup: markup.json
- image dir: Bags/BagsStage8/images
  markup: markup.json
